apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"provisioner","namespace":""},"rules":[{"apiGroups":[""],"resources":["pods","namespaces","job"],"verbs":["get","create","watch","list"]}]}
  creationTimestamp: 2018-08-29T15:08:53Z
  name: provisioner
  resourceVersion: "83055"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/provisioner
  uid: 7196bcf9-ab9d-11e8-b0a1-0800270ae9ab
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - job
  verbs:
  - get
  - create
  - watch
  - list
