apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webconsole
  name: webconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webconsole
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webconsole
    spec:
      containers:
      - image: pyconuk-2018-k8s:webconsole
        name: webconsole
        ports:
          - name: http
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webconsole
  labels:
    app: webconsole
spec:
  type: NodePort
  ports:
  - name: webconsole
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: webconsole
