apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioner
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - "batch"
  resources:
    - jobs
  verbs:
    - get
    - create
    - delete
    - watch
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provisioner
subjects:
- kind: ServiceAccount
  name: provisioner
  namespace: default
roleRef:
  kind: ClusterRole
  name: provisioner
  apiGroup: rbac.authorization.k8s.io
