---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: consolehub
  name: consolehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consolehub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consolehub
    spec:
      containers:
      - image: pyconuk-2018-k8s:consolehub
        name: consolehub
        ports:
          - name: http
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: consolehub
  labels:
    app: consolehub
spec:
  type: NodePort
  ports:
  - name: consolehub
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: consolehub
