---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consolehub
  annotations:
    kubernetes.io/change-cause: "decouple from kubernetes"
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: consolehub
    spec:
      containers:
      - image: pyconuk-2018-k8s:consolehub-step4
        name: consolehub
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: REDIS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: consolehub-config
              key: redis.hostname
---
apiVersion: v1
kind: Service
metadata:
  name: consolehub
spec:
  type: NodePort
  ports:
  - name: consolehub
    port: 80
    targetPort: http
  selector:
    app: consolehub
