---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consolehub
data:
  settings.yaml: |-
    REDIS: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: consolehub
  name: consolehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consolehub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consolehub
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: consolehub
      containers:
      - image: pyconuk-2018-k8s:consolehub-step4
        name: consolehub
        ports:
          - name: http
            containerPort: 5000
        volumeMounts:
          - mountPath: "/etc/consolehub"
            name: config-volume
        env:
        - name: SETTINGS
          value: /etc/consolehub/settings.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: consolehub
  labels:
    app: consolehub
spec:
  type: NodePort
  ports:
  - name: consolehub
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: consolehub
