---
apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioner
data:
  redis.hostname: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: provisioner
    spec:
      containers:
      - image: pyconuk-2018-k8s:provisioner
        name: provisioner
        args:
          - provisioner
        env:
        - name: REDIS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: provisioner
              key: redis.hostname
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-monitor
    spec:
      containers:
      - image: pyconuk-2018-k8s:provisioner
        name: pod-monitor
        args:
          - pod-monitor
        env:
        - name: REDIS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: provisioner
              key: redis.hostname
